### ISSUE TITLE
Crisper fonts

### ISSUE THREAD

**Issue by rwdaigle** [spreedly/engineering-blog#1]
I'd like the Engineering blog to convey a sense of precision and cleanliness. When I look at the current design, the fonts seem a bit big and bleedy (especially the code snippet fonts which are all bold). Can we use a more precise font in general, and especially the code parts?

**Comment by danewesolko** [comment]
@rwdaigle I adjusted the typefaces a bit I think you might like these. They look crisper and more polished as opposed to the default Arial, Helvetica, sans-serif stack. 

I also adjusted the `<code>` typeface and weight.

Update locally and run middleman so you can side-by-side compare.

**Comment by rwdaigle** [comment]
I'll update the project locally this one time, but in the future a screenshot would be awesome?

_/me is a lazy manager_

**Comment by danewesolko** [comment]
screenshot smeanshot.

**Comment by rwdaigle** [comment]
🚢

**Comment by danewesolko** [comment]
that was easy.
