### ISSUE TITLE
RSS or Atom feed of the blog

### ISSUE THREAD

**Issue by duff** [spreedly/engineering-blog#13]
We need to have that.  Yes, it's still a thing!

**Comment by danewesolko** [comment]
seems like this forum feed has some good info regarding this

https://forum.middlemanapp.com/t/creating-an-rss-xml-feed/34/10

**Comment by danewesolko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RSS feed Engineering Blog](https://trello.com/c/yMZr3mhK/78-rss-feed-engineering-blog)

**Comment by rwdaigle** [comment]
Follow up w/ Steven when it's ready?

https://twitter.com/stevenproctor/status/806528122782883840

**Comment by danewesolko** [comment]
confirmed.

**Comment by danewesolko** [comment]
@rwdaigle so it seems that middleman blog actually has a built in helper that was active and accessible via http://engineering.spreedly.com/feed.xml. i'm not 100% familiar with creating rss feeds so i wanted to know if this is correct and if anything further needed to be done.

there are a couple instances where i noticed that information is not being pulled in correctly and i'm not sure how to go about handling this. 

<img width="386" alt="screen shot 2016-12-08 at 4 01 08 pm" src="https://cloud.githubusercontent.com/assets/17124948/21027638/b731f1de-bd5f-11e6-950d-8370d6508360.png">

**Comment by rwdaigle** [comment]
@danewesolko looks like you can just edit this file? https://github.com/spreedly/engineering-blog/blob/master/source/feed.xml.builder

**Comment by danewesolko** [comment]
to confirm RSS has been added to engineering.spreedly.com. will follow up with Steven (https://twitter.com/stevenproctor/status/806528122782883840)

<img width="1025" alt="screen shot 2017-01-17 at 11 52 39 am" src="https://cloud.githubusercontent.com/assets/17124948/22030408/857793fe-dcab-11e6-99b0-9d4505821845.png">
