### ISSUE TITLE
Add ability to link author's name to URL

### ISSUE THREAD

**Issue by rwdaigle** [spreedly/engineering-blog#2]
Just add `author_url` to front matter data so we can provide author links to Twitter/GH etc...

**Comment by danewesolko** [comment]
do we want their name to become a link to their profiles or should it display as an additional line item with an icon?

**Comment by danewesolko** [comment]
screenshot

https://www.dropbox.com/s/krz5m5zus809tlx/Screenshot%202016-06-07%2015.48.44.png?dl=0

**Comment by rwdaigle** [comment]
pls include a screenshot inline like so?

``` markdown
![](https://url.to.image)
```

> do we want their name to become a link to their profiles or should it display as an additional line item with an icon?

I am for just having the name become a link?

**Comment by danewesolko** [comment]
ok. ok.

**Comment by danewesolko** [comment]
done
