### ISSUE TITLE
Provision SSL cert/endpoint

### ISSUE THREAD

**Issue by rwdaigle** [spreedly/engineering-blog#8]
@spreedly/sre in setting up the Engineering Blog we need to provision an SSL cert (I believe we're still doing one per domain?) and add it to the app on Heroku.

Heroku has a new (free) SSL endpoint offering we should explore as it will save $20/month, if it meets with your approval? https://devcenter.heroku.com/articles/ssl-beta

Heroku Dashboard for the blog can be found here: https://dashboard.heroku.com/apps/spreedly-engineering/resources

This will also involve a DNS update once the SSL endpoint is provisioned...

**Comment by micha3lbrown** [comment]
https://github.com/spreedly/ops/issues/1270
https://github.com/spreedly/ops/issues/1293

DNS and SSL certificates have been provisioned.

**Comment by micha3lbrown** [comment]
@rwdaigle 

Can you verify that these are the correct domains I should provision SSL certs for? 
- `spreedly-engineering.spreedly.com`
- `spreedly-engineering-staging.spreedly.com`

**Comment by rwdaigle** [comment]
@micha3lbrown it will be only one domain: `engineering.spreedly.com` (which will point to the `spreedly-engineering` app on Heroku). It's not necessary to get an SSL cert for the staging app since its functionality is not affected by SSL access.

**Comment by micha3lbrown** [comment]
```
▸    Heroku SSL Beta is full, please try again later.  If you need SSL right now, we recommend checking our SSL:Endpoint add-on.
```

The beta is full, continuing with normal SSL installation.

**Comment by micha3lbrown** [comment]
✅ https://engineering.spreedly.com/ is now active!

**Comment by rwdaigle** [comment]
Thank you, @micha3lbrown!
